language: en-AU
reviews:
  high_level_summary: true
  request_changes_workflow: false
  path_filters:
    - terraform/**
    - cloudformation/**
    - marketplace/**
    - .github/**
    - iam-policy.json
